### ISSUE TITLE
[PE-D] Only Alphanumeric Tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-3/tp#143]
>  Features that don't fit well with the product

![Screenshot 2021-10-29 at 4.34.55 PM.png](https://raw.githubusercontent.com/kaixin-hc/ped/main/files/0a19ebbb-a7a6-4ef3-bf04-374362a1c623.png)

* I believe this is overly strict validation. I can think of many use cases where I would want to tag with tags that have spaces in them
* I'm not sure if you're allowed to fix this, but if you are it's relatively simple! just change the regex

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: kaixin-hc/ped#4

**Comment by pss-coder** [comment]
an alternative is set tags to be up to N characters.
